### ISSUE TITLE
Upload a bill, choose a shipment key and Save it without error.

### ISSUE THREAD

**Issue by glind** [TransparentPath/buildly-react-template#170]
Get an error when trying to save an uploaded file on the Shipment Key tab. The .pdf appears to upload (I can see it when it's uploading), the box for choosing a shipment key appears and then the drop down successfully populates with the correct key. Saving the document generates a red error message that says, "Couldn't upload bill due to some error."

**Comment by yasmin2496** [comment]
@RadhikaPPatel Issue resolved
**Cause**: AWS access permissions
**Resolution**: Created a generic account on AWS and updated helm chart accordingly
