### ISSUE TITLE
Show only datum where report is being changed.

### ISSUE THREAD

**Issue by RadhikaPPatel** [TransparentPath/buildly-react-template#192]
Instances where there's no data for some areas due to a single variation (such as sudden shock, tilt, etc.), leave the values that haven't changed blank so that the user sees only the datum that is being reported as changed.

**Comment by glind** [comment]
Temperature still showing at 32 degrees Farenheit, but other values are showing null, as expected.

**Comment by RadhikaPPatel** [comment]
Changes needed in BE. Will test once done in BE.

**Comment by yasmin2496** [comment]
Backend ticket - https://github.com/TransparentPath/sensor_service/issues/115
