### ISSUE TITLE
PDF and Key Value should work independent of each other as well.

### ISSUE THREAD

**Issue by RadhikaPPatel** [TransparentPath/buildly-react-template#195]
PDF used by the customer to determine the Shipment Key has a carriage return between the Key and the Key value on the PDF so no Shipment Key shows up as an option in the Key-Value drop-down box

**Comment by glind** [comment]
Please confirm, the label values pairs appear to require a PDF per label value pair.  It does not appear to be possible to add just label value pair without at least one PDF and to add a second label value pair requires a second PDF.

**Comment by RadhikaPPatel** [comment]
Need to add the ability to allow multiple label value pairs.
