### ISSUE TITLE
Push notifications for alerts using WebSockets

### ISSUE THREAD

**Issue by yasmin2496** [TransparentPath/buildly-react-template#220]
- [x] Make changes in the code as per the changes in BE.
- [x] Add service workers/modules to handle push notifications (used package instead of service worker).
- [x] Move Push Notification outside the need to be logged in.
- [x] Add option to subscribe to different types of notifications (email, push, etc) at different levels (geofence, environmental, etc).
- [x] Integrate Test

**Comment by RadhikaPPatel** [comment]
@glind Can you please check these questions and let us know your thoughts on them?
https://www.notion.so/5th-July-2021-3e68eb1d6fb64481885c20c61b495778#390c0d5f39b547ceb708106d8d251966
