### ISSUE TITLE
Default Sort Order

### ISSUE THREAD

**Issue by glind** [TransparentPath/buildly-react-template#226]
Overview of the feature
The sort order of the columns in each tab should be logical to the user

Business motivation
I want to easily find information I'm looking for from columns that are sorted in a logical order.

User stories / Jobs To Be Done
As a typical user, I want the sort order of the columns in each tab (Shipments, Items, Custodians, Gateways & Sensors, Reporting) to make sense to me so that I can quickly find the information I'm looking for.

Shipments
When I look at shipments in the Shipment tab I want to view them in chronological order from most recent to least recent. "Planned" shipments should be sorted by Estimated Departure Date & Time, "Enroute" shipments should be sorted by Actual Departure Date & Time and "Completed" shipments should be sorted by Actual Arrival Date & Time.

Items
When I view items in the Items tab I want to see them sorted alphabetically by Item Name from A-Z.

Custodians
When I view custodians in the Custodians tab I want to see them sorted alphabetically by Name from A-Z.

Gateways & sensors
When I view gateways & sensors in the Gateways & Sensors tab I want them sorted by Status. I would like a drop-down box to choose which sensor platform I want to view (e.g., Tive, ICLP). Once I've chosen the platform I would like to view the Gateways & Sensors by status in this order: Available, Assigned, In-Transit, Unavailable. (confirm this w/Sunil).

Reporting
When I create reports in the Reporting tab I want to choose a shipment from a list of Shipment Names that is sorted in chronological order from most recent to least recent using the Actual Arrival Date & Time.

Links to any documentation should be included on the card, or attached to the card, and checklists can be created to track the tasks or user stories to build the feature.

It might also be useful to attach any customers that have requested or would benefit from this feature so that your sales team can reach out to them when it ships.

**Comment by RadhikaPPatel** [comment]
@glind I have 2 questions here.
For Shipments, Planned and Enroute right now are combined as Active shipments. So do we need to separate this view as well since the sort is on 2 different columns?

For Reporting, Actual Arrival Date and Time comes in (I guess) just for Completed Shipments. So do we need to show only completed shipments in Reporting section? No Active Shipments (Planned or Enroute) should be shown there?

**Comment by glind** [comment]
Leave shipments as is.

Reporting yes show active.. let's leave that as is for now as well

I will need additional context on the gateways.  I think they are talking about sorting based on platform on the assignment screen but not sure.

**Comment by RadhikaPPatel** [comment]
Closing this issue as gateway changes are done as part of another issue
[Shipment add/edit screen changes](https://github.com/TransparentPath/buildly-react-template/issues/232)
