### ISSUE TITLE
Filter the "Associate Gateway" dropdown

### ISSUE THREAD

**Issue by yasmin2496** [TransparentPath/buildly-react-template#275]
**User Description**
[https://trello.com/c/sdnhxTIe/79-show-gateway-location](url)

After discussing with the client, they decided, for now, to filter the list dropdown instead of adding the column referenced in the description. 

**Tasks**
- [x] In Shipment -> Sensors and Gateways" the user wants the  "Associate Gateway" dropdown list to be filtered to only show the gateways available at the first custodian

**Expected Behavior**
1. Select any shipment 
2. Click on Edit icon
3. Click on Sensors & Gateways section in top ribbon
4. Click on the Associate Gateway dropdown
5. The gateway list is filtered to show only gateways that are associated at the first custodian

**Reference**
See closed issue "custody by start"https://github.com/TransparentPath/custodian_service/issues/17

**Comment by karrla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show Gateway Location](https://trello.com/c/sdnhxTIe/79-show-gateway-location)

**Comment by yasmin2496** [comment]
If no custodians are attached to the shipment all available gateways will be shown @karrla

**Comment by karrla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show Available Gateway UUIDs by Custodian](https://trello.com/c/PZuFSMWE/111-show-available-gateway-uuids-by-custodian)
