### ISSUE TITLE
Hide Shipment "Delete" Column and Icon from end-user

### ISSUE THREAD

**Issue by karrla** [TransparentPath/buildly-react-template#284]
**Description**

End users can not delete Shipments, therefore they should not see the Delete column and Icons.

**Acceptance**

Given a user who does not have Admin rights logged in 
When the user is on the Shipment page (app/shipment)
Then the **Delete** column and **trashcan** icons are hidden

**Reference**
https://trello.com/c/E23UYEHb/95-sys-admin-enhancements

**Comment by karrla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sys Admin Enhancements](https://trello.com/c/E23UYEHb/95-sys-admin-enhancements)

**Comment by karrla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Edit Gateway Assignment](https://trello.com/c/v65m3pPp/69-edit-gateway-assignment)

**Comment by yasmin2496** [comment]
@karrla Should this change be reflected at other places also. For example, an end user can update custodians and items as well in the similar fashion. Do we want to focus on that as well here?

**Comment by karrla** [comment]
@yasmin2496 the other sections are still under discussion. Would it be easier to do all the sections at the same time?

**Comment by yasmin2496** [comment]
Yes @karrla it will be easier to take up all the changes together

**Comment by karrla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX Enhancements: Shipments Table](https://trello.com/c/JzyKCtkT/61-ux-enhancements-shipments-table)

**Comment by SiddharthBhansali13** [comment]
The changes are done, PR #298 raised.
