### ISSUE TITLE
Hide Admin Panel Icon

### ISSUE THREAD

**Issue by karrla** [TransparentPath/buildly-react-template#285]
**Description**

The team does not want all users to use the Admin Panel, so non-admins should not see the Admin Panel link under the Setting menu.

**Acceptance**

Given a user who does not have Admin rights logged in
When the user clicks on the Setting icon (gear) 
Then the Admin Panel link is hidden

**Reference**
https://trello.com/c/E23UYEHb/95-sys-admin-enhancements

**Comment by karrla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Edit Gateway Assignment](https://trello.com/c/v65m3pPp/69-edit-gateway-assignment)

**Comment by karrla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sys Admin Enhancements](https://trello.com/c/E23UYEHb/95-sys-admin-enhancements)

**Comment by SiddharthBhansali13** [comment]
This is the current UI:

- When an end-user is logged in, the icon is already hidden:
![image](https://user-images.githubusercontent.com/98338712/155937956-9d2a52d4-a55d-4c50-84fb-99ce45a78962.png)

- When a super-admin/admin is logged in, the icon is there:
![image](https://user-images.githubusercontent.com/98338712/155938881-9dd68f3b-12fb-4c2a-9040-24b3f2338efe.png)

What is the further requirement here?

**Comment by yasmin2496** [comment]
@glind @karrla Can you look into this and let us know if any change is needed here?

**Comment by yasmin2496** [comment]
closing as stale issue
