### ISSUE TITLE
Fix TP Shipment create/update/delete issue

### ISSUE THREAD

**Issue by abhishek-kumar-piyush** [TransparentPath/buildly-react-template#292]
FE breaks while trying to edit shipment, it gives timeout error 502

- [x] fix timeout error for shipment completed
- [x] fix timeout error for shipment cancelled
- [x] fix timeout error for shipment deletion

Proposed Solution :
Instead of calling Sensor service from shipment service in back-end whenever shipment is created/edited/deleted, call sensor service (update gateway) from front-end with device id.
This way whenever a change is made in shipment, it won't have to wait for sensor service to return which will eventually avoid timeout error

**Comment by yasmin2496** [comment]
@abhishek-kumar-piyush Any updates on this?

**Comment by abhishek-kumar-piyush** [comment]
@yasmin2496 for shipment cancelled/completed, TIVE changes device status (isAttachedToShipment to False) but for delete operation it does nothing.
So after deleting a shipment (which had sensor attached to it), TIVE API still shows isAttachedToShipment as "true", which results in showing gateway is "assigned" to shipment even when shipment is deleted.

Note : I am taking TIVE data as single source of truth i.e. if TIVE shows "isAttachedToShipment" key as false, I am setting sensor status as "available" otherwise I am setting it as true.

**Comment by abhishek-kumar-piyush** [comment]
@karrla when a shipment is cancelled/completed, TIVE changes device status (**isAttachedToShipment** to **False**) but for delete operation it does nothing.
So after deleting a shipment (which had sensor attached to it), TIVE API still shows isAttachedToShipment as "True", which results in showing gateway is "assigned" to shipment even when shipment is deleted.

**Comment by yasmin2496** [comment]
Done in the issue https://github.com/TransparentPath/buildly-react-template/issues/340
