### ISSUE TITLE
Feedback | TP | July 8, 2020

### ISSUE THREAD

**Issue by prabhleen-kaur-hub** [TransparentPath/buildly-react-template#30]
- [x] Move the edit and delete function to the left (instead of right) of the page. Otherwise, need to scroll to find it - not too user friendly. Another option is to make sure everything fits on one page without scrolling

- [x] Mask (grey out) fields that are not being used initially - Alias, GLN, Consortium, etc. until we get feedback.

- [ ] For drop down fields, need to populate the database with proper values so they can displayed appropriately

**Comment by patelradhika** [comment]
stale
