### ISSUE TITLE
Github actions for FE

### ISSUE THREAD

**Issue by abhishek-kumar-piyush** [TransparentPath/buildly-react-template#317]
Create github action for

- [x] unit test
- [ ] read tag name from a file/variable and create tag on github
- [ ] create release (name Release <tag_name from previous step>) and autogenerate release notes
- [ ] create docker images
- [ ] push docker images on gcp/aws based on the requirement.

**Comment by abhishek-kumar-piyush** [comment]
@Mounika is working on this ticket

**Comment by yasmin2496** [comment]
Moved issue to https://github.com/TransparentPath/buildly-react-template/issues/326
