### ISSUE TITLE
Feedback | July 9, 2020

### ISSUE THREAD

**Issue by prabhleen-kaur-hub** [TransparentPath/buildly-react-template#32]
- [x] Fixed the search on various tab. 

- [x] Fixed the map in add shipment. 

- [x] Update sensor placed to "Last known location" in the add sensor form. 

- [x] Add associate gateway column in the sensor table. 
fixed on 07/10/2020

- [x] Remove the "ID" column in general from all the tables. 

- [x] Change the date format to (mm/dd/yyyy)
fixed on 07/10/2020

- [x] Update the spellings that are used in British English to USA English & Customer I"D"
fixed on 07/10/2020

- [x] Sort the drop down values by names
fixed on 07/10/2020

- [x] Update the color of the tags in the map. 

- [x] Place alerts and status at the front of table in shipment dashboard
fixed on 07/09/2020

- [x] Removed alerts should not reappear after coming back to shipment dashboard, they should appear only when page is refreshed. 
fixed 07/13/2020

- [x] In unit of measure  Fields(temperature, weight, distance etc.) in add shipment form should have value selected which is default value of the corresponding class
fixed on 07/10/2020

- [x] Info hover popup in tables in dashboard and map to describe what data they represents.
fixed 07/13/2020 

- [ ] Test it on Edge browser/Internet explorer. 

- [ ] On my account there should be contact information. 

- [x] Forget password story 

- [ ] More mouse-hover hint texts in general. 

- [x] Update the text "Execution" to "Violation"
fixed on 07/10/2020

**Comment by patelradhika** [comment]
stale
