### ISSUE TITLE
BUG: Give users and admins the ability to add a Custodian

### ISSUE THREAD

**Issue by 0785rahul** [TransparentPath/buildly-react-template#335]

**Comment by 0785rahul** [comment]
Expected behavior: 
A regular user or admin should be able to add a new Custodian

Actual behavior:  
Neither a regular user nor an admin can add a new Custodian. Only a Global Admin (Sunil Koduri) is able to add a Custodian. No one else will be granted Global Admin rights. 

The customer, Feeding the NorthWest (FtNW), has reported this bug. The tester can reproduce this bug most of the time. This bug might have an intermittent aspect. However, the tester hasn’t been able to get to the bottom of the intermittency aspect. 

Requested fix: 
Give both regular users and admins the ability to add a Custodian

Steps to reproduce this bug:
1.	Ensure you have user or admin access (not Global Admin access).  
2.	On the side menu, click Custodians.
3.	Click the + Add Custodian button.
4.	In the Add Custodian window, attempt to add a new Custodian. 

<screenshot>

Testing was performed on: https://app.tpath.io/app/

**Comment by 0785rahul** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BUG: Give users and admins the ability to add a Custodian](https://trello.com/c/zOMoSFqa/151-bug-give-users-and-admins-the-ability-to-add-a-custodian)

**Comment by 0785rahul** [comment]
![image](https://user-images.githubusercontent.com/92729520/168225376-b9496628-3043-4577-aa77-a7587c1c74ff.png)

**Comment by yasmin2496** [comment]
@0785rahul This was configuration issue with timeout. It is resolved. Could you get it re-tested once?
User used for testing purpose - dev (This is normal user)
