### ISSUE TITLE
UI Bug Fixes

### ISSUE THREAD

**Issue by TanmayJain92** [TransparentPath/buildly-react-template#387]
- [x] Screen goes blank when expanding planned shipments.

- [x] Replace "Timezone" to "Time Zone".

- [x] Check whether map component is showing organization's default country or not. If not then fix it.

- [x] Check whether country text field is displaying organization's default country or not. If not then fix it.

- [x] Add "Default Time Zone" text field in Register Page and Organization Settings and keep default value to "America/Los_Angeles".

**Comment by patelradhika** [comment]
Merged by PR #388
