### ISSUE TITLE
Shipment and Account Settings Fixes

### ISSUE THREAD

**Issue by TanmayJain92** [TransparentPath/buildly-react-template#389]
- [x] In Account Settings, make WhatsApp Alerts look like SMS Alerts

- [x] In Registration, make WhatsApp Alerts look like SMS Alerts

- [x] Add Timezone below email in Personal Information in Account Settings and make it dropdown and also add update functionality

- [x] In Register Screen, check the spacing of default time zone

- [x] In Graph Component, remove the circle points for max and min lines

- [x] Check for valid token in Private.route.js file so that user navigates to login page if token is expired.

- [x] Update GDPR according to Trello Card.

- [x] In Shipments, also add a text displaying whether shipment started, shipment arrived and shipment completed date and time is actual or expected.

- [x] In Shipments, split the alerts into active and arrived. If shipment is not arrived, then all the alerts comes under arrived alerts. If shipment is in arrived state, then, alerts between shipment started and shipment arrived are arrived alerts and remaining alerts are active alerts. Arrived alerts are shown in between shipment started and shipment arrived. Active alerts are shown in between shipment arrived and shipment completed.

- [x] In Shipments, when we expand a shipment, we see last reading with all the tracker readings. In this, if there's any data that is not available, then display "Irregular Transmission" below last reading and display the readings that are available. Also make the heading bold and italic. Also remove "N/A" for all the readings data.

- [x] In Reporting section, we have sensor report section. In this, if there's any data that is not available, remove "N/A" and keep the values to bold and italic (excluding battery level and location).

**Comment by patelradhika** [comment]
Closed in PR #391
