### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by TanmayJain92** [TransparentPath/buildly-react-template#392]
- [x] Add some bottom space in Account Settings
- [x] Remove "N/A" from Map Component in Shipment and Reporting Screen when a shipment is selected
- [x] In Alert Notifications,
       - Change the look of count button like a pill
       - All alerts should be visible and red dot should be visible only for unread notifications
       - Expand notification when clicking outside the count button
- [x] In Organization Settings, add icons for different suppress email options and also change "supress" to "suppress"
- [x] When clicking on a shipment in alert notifications, reporting page should scroll to Alerts section
- [x] In Sensor Report Section, add an indication text for bold/italic sensor report.

**Comment by patelradhika** [comment]
Merged in PR #393
