### ISSUE TITLE
Alerts Issues

### ISSUE THREAD

**Issue by TanmayJain92** [TransparentPath/buildly-react-template#407]
- [x] Update the text “Suppress Temperature Alert Emails“ to “Suppress Temperature Alerts“ (for others too) in Organization Settings.

- [x] Add suppress alert switches in Create Shipment Page where we set the temperatures, humidity, etc. accordingly.

- [x] In create shipment, update the shipment start to current date and time and shipment end to current date and time + 1 day

- [x] In create shipment, make the suppress alerts switches values same as organization alerts switches values by default and if user changes that, it should get override.

- [x] For ProofTracker trackers, measurement and transmission time must be same and cannot be changed.

**Comment by patelradhika** [comment]
Merged in PR #419
