### ISSUE TITLE
Update User Flow

### ISSUE THREAD

**Issue by TanmayJain92** [TransparentPath/buildly-react-template#409]
Update the User Flow UI as follows:

1. Login Page:
- [x] Remove the "Don't have an account? Register" option as user cannot register directly.
- [x] Add eye and eye-close icon in password so that user can toggle to see the password.
- [x] Add a checkbox for "Remember Username".
- [x] Change the text "Forgot password?" to "Forgot Password?".
- [x] If user tries to use "/register" inside the URL, redirect to the Login page.

2. User Management Page:
- [x] Add two buttons: "Add Organization" and "Invite Users".
- [x] "Add Organization" is visible to only Global Admin and "Invite Users" is visible for both Global Admin and Admins.
- [x] "Add Organization" contains a popup for adding an organization with adding its admins too.
- [x] Admin email, org. name and org. abbreviation should be checked for duplicate values and shouldn't exists.
- [x] "Invite Users" contains a popup for inviting users to the platform by providing their emails, organization name and user roles.
- [x] If user logged in as super admin, then "Invite users" will show 3 fields, emails, organization name and user roles and if user logged in as admin, then only 2 fields, emails and user roles as he/she can only add users to its organization only.
- [x] In both the cases, emails can be multiple.

3. Register Page:
- [x] This will open up only if there's a token in the URL.
- [x] Remove the username field and keep email and organization name prepopulated and disabled as it'll come from the token in the URL.
- [x] Make shipment and environmental alerts for email by default "ON".

4. Forgot Password Page:
- [x] Update the validation for checking whether the entered email exists or not.
- [x] If exists, then after sending the reset password link, create a new verification page that email has been sent.
- [x] Also add the proper texts and option to resend the email.
- [x] Also add limit for sending the email.

5. Reset Password Page:
- [x] Add eye and eye close icon for password and confirm password.
- [x] Add validations by adding texts below the password in red color and as user types the password, it gets updated in green color. Also add cross or tick mark icon accordingly.

**Comment by patelradhika** [comment]
Merged in PR #420
