### ISSUE TITLE
Update Custodian

### ISSUE THREAD

**Issue by TanmayJain92** [TransparentPath/buildly-react-template#416]
- [x] In Trackers/Gateways Page, replace the Custodian column title with "Shipper". In Edit Gateway page, replace the "Custodian Type" title to "Shipper" title. Also in dropdown, only shipper values must be displayed rather that displaying all the values.

- [x] In Custodians Page, add a column "Custodian Type" in between "Abbreviation" and "Location" columns.

**Comment by patelradhika** [comment]
Merged in PR #422
