### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by TanmayJain92** [TransparentPath/buildly-react-template#421]
- [x] Remove the added refresh button for fetching gateways as now it is shifted to BE.

- [x] In the app, we're displaying shock first and then light for sensor data so in Reporting page, in the Sensor Report section, change the position of shock and light columns.

- [x] In Shipment Page, we're fetching all the shipment sensors data at the same time which takes time to update the app which decreases the performance so pass a parameter to the API so that it only fetches a particular amount of sensor data when the app loads for the first time and when we click on any shipment, it fetches its sensor data only.

- [x] In create shipments, organization settings, and in add organizations, change the heading from "Suppress Alert Email Settings" to "Alert Settings". Then change the "Suppress Temperature Alerts" to "Temperature Alerts" respectively. Then if there's any tooltip text that is displaying when hovering, also change that text accordingly.

- [x] Make the radius for geofence to be 3 Miles or 5 Kilometers by default.

**Comment by patelradhika** [comment]
Merged in PR #420
