### ISSUE TITLE
User flow fixes

### ISSUE THREAD

**Issue by TanmayJain92** [TransparentPath/buildly-react-template#424]
- [x]  When login, if we add incorrect credentials, we don't receive any error message so add red error message "Incorrect email or password. Try again!" below the password field but above the sign in button and make the inputs' border red.

- [x] When we receive a forgot password email, we navigate to verification page. In that, the resend email timer is 2 minutes which is less as there might be delay in receiving the email so make the timer to 5 minutes.

- [x] While adding users to an organization from admin point of view, user roles are not displayed.

- [x] Add Jump to Page in all data tables.

- [x] While expanding shipments in shipment page, last location and last reading sometimes not displaying.

**Comment by patelradhika** [comment]
Merged in PR #425
