### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by TanmayJain92** [TransparentPath/buildly-react-template#426]
- [x] In Map component, fix the pins that are displaying as the latest pin is on top so for example, we get a temperature excursion alert and then it recovers at the same location, then we see the green pin for recovery rather than the red pin for the alert.

- [x] In the top bar where we can change the organization, there are currently all organizations and we want to display only organizations having type as producers.

**Comment by patelradhika** [comment]
Merged in PR #427
