### ISSUE TITLE
Send users organization uuid in each get request.

### ISSUE THREAD

**Issue by glind** [TransparentPath/buildly-react-template#43]
The multi-tenant architecture requires core organization filters for each end point so custodians, shipments and sensor gateways can be filtered on the front end based on the users organization.

**Comment by yasmin2496** [comment]
- [ ] Add in Dashboard endpoints
- [ ] Add in Shipments endpoints
- [ ] Add in Items endpoints
- [ ] Add in Gateway endpoints
- [ ] Add in Sensor endpoints

**Comment by yasmin2496** [comment]
1. Here, the filters are added for list operations happening on the loading of the page. However, whenever there is Add, Edit or Delete the List API is called again.  This leads to an extra API call instead we can fetch the newly added or edited object from the API response itself after some modifications at the backend.  
2. The API calls are made from saga as well from the page itself. Please suggest if the same is to be continued or a code cleanup is needed here

**Comment by andrewshortall** [comment]
@yasmin2496 Sorry for the late response. I think a cleanup here would be great. I'd like to get the project in good shape as we move forward.

**Comment by yasmin2496** [comment]
@andrewshortall Sure I will clean up and then move forward here
