### ISSUE TITLE
Admin Panel - Import Section 2

### ISSUE THREAD

**Issue by glind** [TransparentPath/buildly-react-template#54]
A new admin section needs to be crated in the UI to manage import data both from the ICLP or other sensor data endpoints as well as import from JSON REST services or CSV/Excel files for lists of products and Items.

- [x] Data to be imported for - UI.
- [x] API URL - UI.
- [x] API Key - UI.
- [x] Show list of columns in our tables and response for mapping.
- [x] Query API with details from the user and show response on UI.
- [x] Ask the user to input field names for mapping.
- [x] Integrate with BE.

**Comment by yasmin2496** [comment]
@glind  As mentioned in https://github.com/TransparentPath/shipment_service/issues/10 an API endpoint will be made available for importing data from other sources (REST service or CSV/ Excel). Few questions regarding this
1. The Admin section has to be a separate section below User Management or inside User Management as a new tab?
2. Is this going to be a place where Admin can specify what he/she intends to import - A field where they can choose for JSON REST service or CSV/Excel file and let them input as per theirs selection?
3. Any other config to be required here?
4. For CSV/Excel file imports, do we have a specific format which should be allowed? Similarly, any format on JSON request that should be accepted?
5. Products and Items import to be done separately or part of single request?

**Comment by yasmin2496** [comment]
@glind As per our previous discussion
1. We need a mapping screen to be shown where we pick up first row from CSV/Excel file as Headers and give the users a provision to map the `headers` to `columns`
Some pending points
1. The Admin section has to be a separate section below User Management or inside User Management as a new tab?
2. Is this going to be a place where Admin can specify what he/she intends to import - A field where they can choose for JSON REST service or CSV/Excel file and let them input as per theirs selection?
3. CSV/ Excel file will work on validation based template. Any format on JSON request that should be accepted?
4. Products and Items import to be done separately or part of single request?

**Comment by yasmin2496** [comment]
- [ ] Finalize the design for Admin Console - Consolidated dashboard / Subsection in each section
- [ ] Update existing polling timeout for the sensor. Need an API endpoint exposed for the same
- [ ] CRUD operations for Units of Measure
- [ ] CRUD operations for Item type
- [ ] CRUD operations for Product type
- [ ] CRUD operations for Sensor type
- [ ] CRUD operations for Gateway type

**Comment by glind** [comment]
I think we will need CRUD views for Product as well as Product Type correct?  We can currently import a product or create an item with a product in the item section but we don't have the ability to do CRUD operation on the Product itself except for in the Django Admin.

**Comment by RadhikaPPatel** [comment]
- [ ] Import UI (from Third-party API).
- [ ] Integrate with BE.
