### ISSUE TITLE
When adding shipments users are forgetting to save before closing pop-over

### ISSUE THREAD

**Issue by glind** [TransparentPath/buildly-react-template#70]
When adding shipments users are forgetting to save before closing pop-over, click next in wizard should have data saved, warnings should pop-up if closing window before save.

- [x] Ensure that the user has 'Save' and 'Save & Next' behaviour in each step of the form
- [x] There should be no data loss occurring

**Comment by yasmin2496** [comment]
![Screenshot 2021-02-11 at 11 11 06](https://user-images.githubusercontent.com/61192422/107605725-02841880-6c5a-11eb-930a-2af772653a4c.png)
![Screenshot 2021-02-11 at 11 11 33](https://user-images.githubusercontent.com/61192422/107605731-057f0900-6c5a-11eb-8c71-89762c0f8ba6.png)
![Screenshot 2021-02-11 at 11 11 48](https://user-images.githubusercontent.com/61192422/107605733-06179f80-6c5a-11eb-950e-215c23efcfe5.png)

**Comment by glind** [comment]
Form is still not saved when clicking next, and pop-up doesn't seem to be applied universally.
