### ISSUE TITLE
Use Data table (for shipment page only)

### ISSUE THREAD

**Issue by yasmin2496** [TransparentPath/buildly-react-template#80]
- [x] Modify code to use DataTables rather than normal Material UI table.
- [x] Modify UI as per what it is right now.
- [x] Code for search, sort, filter, pagination functionality.
- [x] Check above functionality works fine.

**Comment by RadhikaPPatel** [comment]
@glind I have one question. We have search, filter, and sort in place for Shipments. So do we need the same UI (Sort and Filter buttons) for Items, Custodians, and Gateways?
